const dataSet = [{
    "id": 1,
    "usageDate": "5/20",
    "percentage": 29
  }, {
    "id": 2,
    "usageDate": "3/20",
    "percentage": 56
  }, {
    "id": 3,
    "usageDate": "1/20",
    "percentage": 85
  }, {
    "id": 4,
    "usageDate": "12/19",
    "percentage": 75
  }, {
    "id": 5,
    "usageDate": "1/20",
    "percentage": 81
  }, {
    "id": 6,
    "usageDate": "3/20",
    "percentage": 70
  }, {
    "id": 7,
    "usageDate": "9/19",
    "percentage": 58
  }, {
    "id": 8,
    "usageDate": "7/20",
    "percentage": 75
  }, {
    "id": 9,
    "usageDate": "6/20",
    "percentage": 46
  }, {
    "id": 10,
    "usageDate": "1/20",
    "percentage": 36
  }, {
    "id": 5,
    "usageDate": "1/20",
    "percentage": 81
  }, {
    "id": 6,
    "usageDate": "3/20",
    "percentage": 70
  }, {
    "id": 7,
    "usageDate": "9/19",
    "percentage": 58
  }, {
    "id": 8,
    "usageDate": "7/20",
    "percentage": 75
  }, {
    "id": 9,
    "usageDate": "6/20",
    "percentage": 46
  }, {
    "id": 10,
    "usageDate": "1/20",
    "percentage": 36
  }
]
  
export  default dataSet